CREATE DATABASE Sales
GO

USE Sales
GO

CREATE TABLE CATEGORY(
       CategoryId  INT   IDENTITY(1,1),
       CategoryName NVARCHAR(50)   NOT NULL,
       CONSTRAINT PK_DEPARTMENT PRIMARY KEY(CategoryId)
) 
GO

CREATE TABLE ITEM(
       ItemId  INT   IDENTITY(1,1),
       ItemName NVARCHAR(50)   NOT NULL,
       CategoryId  INT,
       ItemPrice DECIMAL(18,0)   NOT NULL,
       ItemImageName NVARCHAR(50),
       CONSTRAINT PK_ITEM PRIMARY KEY(ItemId),
       CONSTRAINT FK_ITEM_CATEGORY  
	   FOREIGN KEY(CategoryId) 
	   REFERENCES CATEGORY(CategoryId) 
	   ON DELETE SET NULL,
)  
GO

INSERT INTO CATEGORY(CategoryName)VALUES('IPHONE')
INSERT INTO CATEGORY(CategoryName)VALUES('SAMSUNG')
INSERT INTO CATEGORY(CategoryName)VALUES('NOKIA')
INSERT INTO CATEGORY(CategoryName)VALUES('XIAOMI')
