//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranHoaiSon_19DH110901_Lab4_LTWNC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public decimal ItemPrice { get; set; }
        public string ItemImageName { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
